### ISSUE TITLE
Update to 2.1.4 now says that ionRangeSlider is not a function in Aurelia

### ISSUE THREAD

**Issue by cdaniel77** [IonDen/ion.rangeSlider#374]
The slider was working perfectly in 2.1.3 but since I upgraded.  I cannot get the slider to work with Aurelia.  I keep getting that the $(...).ionRangeSlider is not a function error.

```
import 'ion-rangeslider';

export class MyClass{
    $('#dateRangeSlider').ionRangeSlider();
}
```

**Comment by IonDen** [comment]
Maybe you forgot to import jquery here?

**Comment by cdaniel77** [comment]
jQuery is installed or it wouldn't have worked with 2.1.3.

**Comment by IonDen** [comment]
Please check this commit: https://github.com/IonDen/ion.rangeSlider/pull/369/files
if think it brakes your code. What do you think about it?

**Comment by Robert-W** [comment]
Hi I can confirm the same issue, I was on 2.1.2 and everything worked.  I am also getting multipleDefine errors in our application which is using the Esri JavaScript API (built on Dojo so it uses Dojo's AMD loader).  I can confirm we load jQuery as a script before we load the Esri API with dojo's loader.

I definitely agree that the commit you linked is the culprit.  I can fix the multipleDefine error by aliasing jquery in my dojoConfig like so:
```javascript
var dojoConfig = {
  parseOnLoad: false,
  async: true,
  packages: [
    ....
  ],
  aliases: [
    ['jquery', 'vendor/jquery/dist/jquery.min.js'],
    ....
  ],
  deps: ['dojo/domReady!'],
  callback: function () {require(['js/main']);}
};
```

However that does not fix the `TypeError: $(...).ionRangeSlider is not a function` error

**Comment by IonDen** [comment]
Ok, i will investigate this more.

**Comment by IonDen** [comment]
Should be fixed in 2.1.5
